name: run-vrt
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  prepare:
    name: Prepare main branch screenshots
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            yarn.lock

      - name: yarn install
        run: yarn install --frozen-install

  run-vrt:
    name: compare images
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            yarn.lock

      - name: yarn install
        run: yarn install --frozen-install

      - name: screenshots
        run: yarn screenshot

      - name: make .reg dirs
        run: |
          mkdir .reg &&
          mkdir .reg/actual &&
          mkdir .reg/expected

      - name: make screenshots .reg/actual
        run: |
          mv __screenshots__/actual .reg

      - name: make screenshots .reg/expected
        run: |
          mv __screenshots__/expected .reg

      - name: check file
        run: ls

      - name: compare
        run: |
          yarn compare

      - name: out
        run: |
          cat .reg/reg.json

      - name: make comment
        run: |
          node script.js ./.reg/reg.json | cat > comments

      - name: check file
        run: |
          cat comments

      - name: send pr comment if report.html changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          git status | head --lines 1
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git diff --name-only --exit-code ./report.html
          git add ./report.html
          git commit -m 'feat: change report.html'
          git push
          gh pr comment -F ./comments "${URL}"

