name: run-vrt

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: echo hello world
        run: |
          cat << EOF > comments
          ![screen-shot](${URL}/__screenshots__/expected/components/ui/Button/Primary:png?raw=true)
          EOF
        env:
          URL: ${{ github.event.pull_request.html_url }}
      - run: ls
      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run:
          gh pr comment -F ./comments "${URL}"

  resolve-dependency:
    runs-on: ubuntu-22.04
    steps:
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: yarn install
        run: yarn install
      - name: screenshot
        run: yarn screenshot
