name: run-vrt

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: echo hello world
        run: |
          cat << EOF > comments
          hello world
          gg
          EOF
      - run: ls
      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run:
          gh pr comment -F ./__screenshots__/components/expected/components/ui/Image/Primary.png "${URL}"

  resolve-dependency:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compare-no-story
