name: run-vrt
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  prepare:
    name: Prepare main branch screenshots
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            yarn.lock

      - name: yarn install
        run: yarn install --frozen-install

  run-vrt:
    name: compare images
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            yarn.lock

      - name: checkout main branch
        uses: actions/checkout@v3

      - name: screenshots
        run: yarn screenshot

      - name: make screenshots .reg/actual
        run: |
          mv __screenshots__/actual .reg

      - name: check file
        run: ls
