name: run-vrt

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: echo hello world
        run: |
          echo hello world