name: run-vrt
on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  artifact-test-upload:
    name: uploading artifact test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: make text .reg/file
        run: | 
          cat << EOF > .reg/file 
          hello
          EOF
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: .reg

  artifact-test-download:
    name: downloading artifact test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: check files
        run: ls
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: |
          cat .reg/file

  prepare:
    name: Prepare main branch screenshots
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: |
            **/yarn.lock
            yarn.lock
      - name: yarn install
        run: yarn install --frozen-install
      - name: check commit hash
        id: commithas
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: restore reg-suit screenshots
        uses: actions/cache@v2
        with:
          path: .reg/
          key: reg-${{ steps.commithash.outputs.hash }}-v7

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".reg/"

      - name: screenshots main branch
        if: steps.check_files.outputs.files_exists == 'false'
        run: yarn screenshot

      - name: run reg-suit main branch
        if: steps.check_files.outputs.files_exists == 'false'
        run: yarn run reg-suit run

      - name: set reg-suit expected
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          rm -rf .reg/expected/
          mv -f .reg/actual/ .reg/expected/
          mkdir .reg/actual/
          ls -l .reg/
      - name: upload .reg/
        uses: actions/upload-artifact@v2
        with:
          name: reg-expected
          path: .reg/
  resolve-dependency:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: screenshot
        run: yarn screenshot
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || 
          git checkout -b ${GITHUB_REF#refs/heads/} && 
          git pull
      - name: report
        run: yarn run reg-suit run
