name: run-vrt

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

  workflow_dispatch:
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: echo hello world
        run: |
          echo hello world
      - name: notify begin
        run: |
          echo begin switching to working branch
      - uses: actions/checkout@v3
      - name: notify end
        run: |
          echo end switching to working branch
      - name: echo filename
        run: |
          cat package.json
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  resolve-dependency:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: compare-no-story
